import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  if (typeof window !== "undefined") {
    console.log(window.history)
   }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Dani hahó
      <Link href="/about">
          <a>About page</a>
        </Link>
    </div>
  );
};

export default Home;
